# https://hub.docker.com/_/maven/
image: maven:3.8.2-jdk-8

variables:
  MAVEN_CLI_COMMON: "-e -B"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - compile
  - unit-test
  - integration-test

compile-job:
  stage: compile
  script:
    - mvn $MAVEN_CLI_COMMON compile

unit-test-job:
  stage: unit-test
  script:
    - mvn $MAVEN_CLI_COMMON test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

derby-integration-test-job:
  stage: integration-test
  script:
    - mvn $MAVEN_CLI_COMMON -Pit-config,derby verify
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

h2-integration-test-job:
  stage: integration-test
  script:
    - mvn $MAVEN_CLI_COMMON -Pit-config,h2 verify
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

hsqldb-integration-test-job:
  stage: integration-test
  script:
    - mvn $MAVEN_CLI_COMMON -Pit-config,hsqldb verify
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

mssql41-integration-test-job:
  stage: integration-test
  services:
    - name: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      alias: sqlserver
  variables:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: y0urStrongPassword
    MSSQL_PID: Express
  script:
    - curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
    - apt-get update && apt-get install -y mssql-tools unixodbc-dev
    - /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P y0urStrongPassword -i dbunit-docker/sqlserver/mssql-setup.sql
    - mvn $MAVEN_CLI_COMMON -Pit-config,mssql41 verify -Ddbunit.profile.url=jdbc:sqlserver://sqlserver:1433;DatabaseName=dbunit;SelectMethod=cursor
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

mysql-integration-test-job:
  stage: integration-test
  services:
    - name: mysql/mysql-server:5.7
      alias: mysql
  variables:
    MYSQL_DATABASE: dbunit
    MYSQL_USER: dbunit
    MYSQL_PASSWORD: dbunit
    MYSQL_ROOT_PASSWORD: dbunit
    TZ: "America/Chicago"
  script:
    - mvn $MAVEN_CLI_COMMON -Pit-config,mysql verify -Ddbunit.profile.url=jdbc:mysql://mysql:3306/dbunit
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

oracle-ojdbc8-integration-test-job:
  stage: integration-test
  services:
    - name: dbunit/dbunit-it-oracle11g:1.0.1
      alias: oracle11gJdbc8
  variables:
    TZ: "America/Chicago"
  script:
    - sleep 1m
    - mvn $MAVEN_CLI_COMMON -Pit-config,oracle-ojdbc8 verify -Ddbunit.profile.url=jdbc:oracle:thin:@oracle11gJdbc8:1521:XE
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml

postgresql-integration-test-job:
  stage: integration-test
  services:
    - name: postgres:9.6
      alias: postgres
  variables:
    POSTGRES_DB: dbunit
    POSTGRES_USER: dbunit
    POSTGRES_PASSWORD: dbunit
  script:
    - mvn $MAVEN_CLI_COMMON -Pit-config,postgresql verify -Ddbunit.profile.url=jdbc:postgresql://postgres/dbunit
  artifacts:
    when: always
    reports:
      junit:
        - target/failsafe-reports/TEST-*.xml
