/**

 Create tables used to test ImportedAndExportedKeysSearchCallback's ordering algorithm with 
 the following dependencies:

    A - B
    |
    C    D - E
          \ /
           F  
	     
 
*/

CREATE TABLE A
  (PKA NUMERIC NOT NULL,
   FKB NUMERIC,
   PRIMARY KEY (PKA));

CREATE TABLE B
  (PKB NUMERIC NOT NULL,
   PRIMARY KEY (PKB));

CREATE TABLE C
  (PKC NUMERIC NOT NULL,
   FKA NUMERIC,
   PRIMARY KEY (PKC));

CREATE TABLE D
  (PKD NUMERIC NOT NULL,
   FKE NUMERIC,
   FKF NUMERIC,
   PRIMARY KEY (PKD));

CREATE TABLE E
  (PKE NUMERIC NOT NULL,
   FKF NUMERIC,
   PRIMARY KEY (PKE));

CREATE TABLE F
  (PKF NUMERIC NOT NULL,
   PRIMARY KEY (PKF));

ALTER TABLE A ADD CONSTRAINT AB FOREIGN KEY (FKB) REFERENCES B (PKB);

ALTER TABLE C ADD CONSTRAINT CA FOREIGN KEY (FKA) REFERENCES A (PKA);

ALTER TABLE D ADD CONSTRAINT DE FOREIGN KEY (FKE) REFERENCES E(PKE);
ALTER TABLE D ADD CONSTRAINT DF FOREIGN KEY (FKF) REFERENCES F (PKF);

ALTER TABLE E ADD CONSTRAINT EF FOREIGN KEY (FKF) REFERENCES F (PKF);
