name: Publish docs to GitHub pages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build AsciiDoc Pages
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        source_dir: docs/ # default is .
        pdf_build: true
        # asciidoctor_params: --attribute=nofooter
        # adoc_file_ext: .ascii # default is .adoc
        # slides_build: true
        # pre_build:
        # post_build:
